### ISSUE TITLE
Event Model link goes to Bluesky

### ISSUE THREAD

**Issue by teddyrendahl** [bluesky/bluesky.github.io#10]
https://github.com/bluesky/bluesky.github.io/blob/007494d3c4d1a55395afd81aecc3da5bb24059f8/index.html#L40

Was this mean to go elsewhere?

**Comment by danielballan** [comment]
Yes, I think that was a copy/paste error. It was meant to go to our (relevantly new) [event-model documentation](https://blueskyproject.io/event-model/) which explains the schemas and some convenience functions for composing, validating, and transforming documents.
