### ISSUE TITLE
Update the UI, and some effects.

### ISSUE THREAD

**Issue by mohittk** [bluesky/bluesky.github.io#15]
I am going to add some hover effects to buttons, some changes in font, and background changes at alternative section.

**Comment by mrakitin** [comment]
Can you please provide more context and the exact issues with the current UI?

**Comment by mohittk** [comment]
> Can you please provide more context and the exact issues with the current UI?

Yea! sure.

**Comment by mrakitin** [comment]
Please note, the documentation is generated with sphinx. Would it make sense to submit a PR to https://github.com/sphinx-doc/sphinx instead?

**Comment by mohittk** [comment]
> Please note, the documentation is generated with sphinx. Would it make sense to submit a PR to [sphinx-doc/sphinx](https://github.com/sphinx-doc/sphinx) instead?

Umm.. its allright, I'll withdraw the issue. Please remove the invalid label.
