### ISSUE TITLE
Stale "Related Projects" Links

### ISSUE THREAD

**Issue by ZLLentz** [bluesky/bluesky.github.io#20]
https://github.com/bluesky/bluesky.github.io/blob/1ca55fcf86587d9ce44afd40a0c964f99528ae1e/index.html#L64-L68

- Skywalker is defunct
- Need to rename typhon to typhos

We can add other repos here, there surely are a lot

- apstools
- happi
- lots of others

Pete made a good point that we should also link to these from the github org

**Comment by ZLLentz** [comment]
I'm happy to make the PR but I don't know a full or even partially complete scope of links to add

**Comment by danielballan** [comment]
The list is really helpful! Thanks @ZLLentz.

**Comment by ZLLentz** [comment]
I'll make a PR today with at least the changes/additions I know about :+1:

**Comment by prjemian** [comment]
I started a branch (https://github.com/bluesky/bluesky.github.io/tree/add-apstools) on Friday but did not make a PR yet.  You might combine my additions (alphabetical sort, then added apstools to the list).  With that, my branch could be dumped.

**Comment by ZLLentz** [comment]
Sure, I'll start from yours Pete
