### ISSUE TITLE
Add document website URL to github repo

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky.github.io#7]
good to have this link at the top of the page: https://blueskyproject.io/
Here is the page where it is added: https://github.com/bluesky/bluesky.github.io, next to the description text

**Comment by prjemian** [comment]
Done.  Looky here: https://blueskyproject.io/

**Comment by prjemian** [comment]
Actually, look here: https://github.com/bluesky/bluesky.github.io which links you that other one.

**Comment by danielballan** [comment]
Thanks, @prjemian! Prompted by this, I went through and updated the links in bluesky, ophyd, databroker, event-model, suitcase-core,and intake-bluesky from nsls-ii.github.io/* to blueskyproject.io/*.
